temperature = 18.0
humidity = 60
cur_temp = 23
cur_hum = 51
modes = ['cool', 'quick_cool', 'dehumidify', 'fan', 'heat']
current_mode_index = 1
wind_speed = ['low', 'medium', 'hight']
current_wind_index = 0
page = 0
stateAC = True
status = False
current_Temp_DHT22 = 0
numberpage = 0
time_on = 0
time_set = False