temperature = 30.0
humidity = 0
cur_temp = 26
cur_hum = 50
modes = ['cool', 'time', 'night', 'power', 'dry']
current_mode_index = 1
wind_speed = ['low', 'medium', 'hight']
current_wind_index = 0
page = 0
stateAC = True
status = False
numberpage = 0
time_on = 0
time_set = False
