temperature = 29.0
humidity = 60
cur_temp = 29
cur_hum = 52
modes = ['cool', 'time', 'night', 'power', 'dry']
current_mode_index = 3
wind_speed = ['low', 'medium', 'hight']
current_wind_index = 0
page = 1
stateAC = True
status = True
numberpage = 0
time_on = 0
time_set = False
